### ISSUE TITLE
Error when running program with "detailed_place_flag" : 1

### ISSUE THREAD

**Issue by magic3007** [rachelselinar/DREAMPlaceFPGA#12]
Hi there! I'm facing an issue while running the program with the `detailed_place_flag` set to  1. I noticed that this flag is supposed to enable detailed placement of the program, but it seems to be causing an error. Could you help me understand what might be causing this issue?

I'm currently running the program with the following configuration on ISPD 2016 FPGA01 benchmark. 
```json
{
"aux_input" : "benchmarks/ispd2016/FPGA01/design.aux",
"gpu" : 1,
"num_threads" : 1,
"num_bins_x" : 512,
"num_bins_y" : 512,
"global_place_stages" : [
    {"num_bins_x" : 512, "num_bins_y" : 512, "iteration" : 2000, "learning_rate" : 0.01, "wirelength" : "weighted_average", "optimizer" : "nesterov"}
],
"target_density" : 1.0,
"density_weight" : 8e-5,
"random_seed" : 1000,
"scale_factor" : 1.0,
"global_place_flag" : 1,
"legalize_flag" : 1,
"routability_opt_flag" : 1,
"detailed_place_flag" : 1,
"dtype" : "float32",
"deterministic_flag" : 0,
"result_dir": "results/ispd2016/FPGA01"
}
```
I've included the error message below:
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/30785720/229760425-e376a0a5-654d-4b30-ae6e-0d6a38a7c08f.png">

Any guidance or insight you could provide would be greatly appreciated. Thank you for your time!

**Comment by rachelselinar** [comment]
Thank you for raising this issue.

Currently only global placement and packing-legalization stages are available in DREAMPlaceFPGA. The `detailed_place_flag` is currently unavailable and I've updated the code to ensure the tool does not ERROR out when the flag is set.

These are two available modes:
(i) `global_place_flag` = 1 and `legalize_flag` = 0:
    Global Placement is run on DREAMPlaceFPGA, and elfPlace is used to run packing-legalization and detailed placement.
(ii) `global_place_flag` = 1 and `legalize_flag` = 1:
    Global Placement and Packing-Legalization are run on DREAMPlaceFPGA. Detailed placement is not run.

Closing issue.
