### ISSUE TITLE
Runtime Error: cudaErrorInvalidDevice

### ISSUE THREAD

**Issue by keyplay** [rachelselinar/DREAMPlaceFPGA#25]
Hi, there is a runtime error when executing ''python dreamplacefpga/Placer.py test/FPGA-example1.json'' whether enable GPU or not. 

![image](https://github.com/rachelselinar/DREAMPlaceFPGA/assets/5894125/1e663b55-54a9-4396-a4c4-e5f3c5d0172e)

I build env by docker.

May I know if I can get some suggestion?

Thanks for your help.

**Comment by keyplay** [comment]
Sorry, the error only happens when enable GPU

**Comment by rachelselinar** [comment]
Closing issue for now.
Please reopen if you have issue when running on a GPU machine.
