### ISSUE TITLE
Always one instance being placed to "1 0 15" 

### ISSUE THREAD

**Issue by zhilix** [rachelselinar/DREAMPlaceFPGA#5]
When I run global placement and legalization for gnl designs and FPGA-example designs, in the final solution there is always one instrance being placed to  "1 0 15".

![Screen Shot 2023-03-03 at 20 13 58 PM](https://user-images.githubusercontent.com/90161523/222945080-b3ddb1d4-86aa-43be-b462-7dace4baf5a6.png)

![Screen Shot 2023-03-04 at 23 18 27 PM](https://user-images.githubusercontent.com/90161523/222945105-9b6c3ec7-ed3c-4c2c-8cf5-ba7bbffdd4c4.png)

which is very far away from other instances being placed in the center of the layout.

I tried to dump out placement solutions at different stages and found probably something happened during "ripUP_Greedy_slotAssign".

**Comment by rachelselinar** [comment]
Thanks for catching this corner case bug when an instance has only 1 ripUp candidate during legalization. Fix is in to include a check to ensure the instance is legalized during ripUP LG stage, if not it is legalized in a greedy manner.
There are no issues with the large ISPD'16 benchmarks FPGA01-FPGA12.
Closing issue.
